services:
  - type: web
    name: medbuddy-app
    env: python
    plan: free
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn --timeout 120 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: ANTHROPIC_API_KEY
        value: ""
